actions_per_turn=2

# Parametry jednostek
knight_hp=50
knight_range=1
knight_armor=2
knight_speed=6
knight_base_attack=10

archer_hp=30
archer_range=4
archer_speed=4
archer_base_attack=7

mage_hp=20
mage_range=5
mage_speed=3
mage_base_attack=20

# Magic
max_mana=50
spell_mana_cost=10
mana_regen_per_round=5
heal_value=10

# Modyfikatory terenu
forest_cover_reduction=1


